### ISSUE TITLE
The PropertyFieldPeoplePicker Control is not Reactive

### ISSUE THREAD

**Issue by SurinderTaneja** [OlivierCC/spfx-40-fantastics#24]
Whenever I add or remove any value in PropertyFieldPeoplePicker, it doesn't reflect the new value on the page. I have to refresh the page to see it. This is only happening when I test the web part on SharePoint environment but it works in localhost environment.

**Comment by OlivierCC** [comment]
Hi @SurinderTaneja, this happens when you are using the last version of the SPFx package (for example version 1.1.1 of sp-webpart-base). The sp-client-custom-fields will be fix soon to support these packages version. Stay tuned.
Regards,
Olivier

**Comment by OlivierCC** [comment]
Hi @SurinderTaneja,

the problem has been fixed with the version 1.3.5 of the sp-client-custom-field library, now available on github at http://github.com/OlivierCC/sp-client-custom-fields. But be careful, this version changes the custom field declaration. I will republish a new version of the web parts with support of this very soon.

Regards,

Olivier

**Comment by SurinderTaneja** [comment]
Thanks @OlivierCC for your quick response on this. I installed the 1.3.5 version of the sp-client-custom-field library and able to successfully build the solution by adding render:this.render.bind(this) but it still doesn't work with 1.1.1 version of sp-webpart-base. I am currently using the latest version of node(5.0.3) and it shows the below error when I try to enter the name in peoplepicker control. 

Exception in CommandButton.render(): TypeError: Cannot read property 'palette' of undefined.

Regards.
Surinder

**Comment by OlivierCC** [comment]
Hi @SurinderTaneja. Very strange error, i'm not able to reproduce it in my SharePoint sites. This error could come from Office UI Fabric.

Some questions to try to identify the issue:
- What is the kind of your tenant : Dev (MSDN like), First release or normal release ?
- What is the kind of page where the error happens: Workbench (../_layouts/15/workbench), modern page in modern site or classical page in classical site ? Or  every 3 ?
- Can you send me the total stack trace of this exception in your browser ?

Thanks, regards,

Olivier
